import type { ReverseGeocodingResult } from './openMeteoGeocodingClient.ts';

export const REVERSE_GEOCODING_FALLBACKS: ReverseGeocodingResult[] = [
  {
    id: 111,
    name: 'San Francisco',
    latitude: 37.7749,
    longitude: -122.4194,
    country: 'United States',
    country_code: 'US',
    timezone: 'America/Los_Angeles',
    admin1: 'California',
  },
  {
    id: 222,
    name: 'Brooklyn',
    latitude: 40.6782,
    longitude: -73.9442,
    country: 'United States',
    country_code: 'US',
    timezone: 'America/New_York',
    admin1: 'New York',
  },
  {
    id: 333,
    name: 'Austin',
    latitude: 30.2672,
    longitude: -97.7431,
    country: 'United States',
    country_code: 'US',
    timezone: 'America/Chicago',
    admin1: 'Texas',
  },
  {
    id: 444,
    name: 'Zagreb',
    latitude: 45.815,
    longitude: 15.9819,
    country: 'Croatia',
    country_code: 'HR',
    timezone: 'Europe/Zagreb',
    admin1: 'City of Zagreb',
  },
  {
    id: 555,
    name: 'Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    country: 'France',
    country_code: 'FR',
    timezone: 'Europe/Paris',
    admin1: 'Île-de-France',
  },
];
